import DS from 'ember-data';

export default DS.Model.extend({
  uuid: DS.attr("string"),
  title: DS.attr("string"),
  author: DS.attr("string"),
  url: DS.attr("string"),
  site_full: DS.attr("string"),
  site: DS.attr("string"),
  siteSection: DS.attr("string"),
  siteCategories: DS.attr("string"),
  sectionTitle: DS.attr("string"),
  titleFull: DS.attr("string"),
  published: DS.attr("string"),
  repliesCount: DS.attr("string"),
  participantsCount: DS.attr("string"),
  siteType: DS.attr("string"),
  country: DS.attr("string"),
  spamScore: DS.attr("string"),
  mainImage: DS.attr("string"),
  performanceScore: DS.attr("string"),
  domainRank: DS.attr("string"),
  ordInThread: DS.attr("string"),
  text: DS.attr("string"),
  highlightText: DS.attr("string"),
  highlightTitle: DS.attr("string"),
  language: DS.attr("string"),
  externaLinks: "",
  crawled: DS.attr("string")
});
